### PR TITLE
bump python version

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735908736
Fixes: https://github.com/thoth-station/python/issues/323

### CODE REVIEW

**Review by fridex — APPROVED** [review]
:+1: :100:

**Comment by goern** [comment]
@fridex is Prow configuration at https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/thoth-station/config.yaml#L219-L222 wrong? we don't do any checks in this repo?

/retest

**Comment by bissenbay** [comment]
@fridex @harshad16 PTAL

**Comment by harshad16** [comment]
> Prow configuration at https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/thoth-station/config.yaml#L219-L222 wrong? we don't do any checks in this repo?

i will update the prow configuration, and have pre-coommit check and pytest , as this repo dont need build check. 
thanks for pointing it out. :+1:

**Comment by harshad16** [comment]
@bissenbay  can you please relock the pipfile.lock for this repo. thanks

**Comment by bissenbay** [comment]
> @bissenbay can you please relock the pipfile.lock for this repo. thanks

thanks @harshad16 , I have relocked it.

**Review by harshad16 — APPROVED** [review]
thanks :100:

**Comment by harshad16** [comment]
Merging this , pytest issue would be tested in a separate pr.

**Pull request merged**
