### PR TITLE
Update .thoth.yaml

### PR DESCRIPTION
**Pull request by saisankargochhayat**

### CODE REVIEW

**Comment by harshad16** [comment]
@saisankargochhayat hey, have you tested this in some repository?

**Comment by saisankargochhayat** [comment]
@harshad16 I did try it on a sample repo I made - https://github.com/saisankargochhayat/kebechet_sample/issues/7
Kebechet picks up the managers from this format.

**Comment by harshad16** [comment]
ah awesome :medal_sports: 
so kebechet which is running as cronjob can use this format? 
I mean is kebechet updates merged in kebechet?

**Comment by fridex** [comment]
> ah awesome 
> so kebechet which is running as cronjob can use this format?

An event based kebechet will consume this directly from user repositories.

> I mean is kebechet updates merged in kebechet?

Not yet, but the format will remain so I guess it's ok to merge this.

**Pull request merged**
